<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        console.log("第一行代码");
        // 设置延时器
        // 返回一个id
        const timer =  setTimeout(() => {
            console.log("1秒后执行");
        }, 1000);
        console.log("第二行代码");

        setTimeout(() => {
            clearTimeout(timer)
            console.log("中断了 timer 的执行");
        })

        // setinterval 每隔一段事件执行回调
        let interval = setInterval(() => {
            let date = new Date();
            console.log(`${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`);
        }, 1000)

        // 5秒后取消
        setTimeout(() => {
            clearInterval(interval);
        }, 5000)

        
        // promise链式调用 后面then的异常都是可以捕获到的
        const promise = new Promise((resolve, reject) => {
            // 用setTimeout模拟1秒后请求成功
            setTimeout(() => {
                reject("promise 失败")
            }, 1000)
        })
        .then(value => value + 10)
        .then(value => new Promise(resolve => resolve(value + 20)))
        .then(value => console.log(value))
        .catch(error => console.log(error))

        // console.log(promise);

        // all 会按代码的promise执行
        let p1 = new Promise(resolve => {
            setTimeout(() => {
                resolve(1)
            }, 1000)
        })

        let p2 = new Promise(resolve => {
            setTimeout(() => {
                resolve(2)
            }, 2000)
        })

        let p3 = new Promise(resolve => {
            setTimeout(() => {
                resolve(3);
            }, 500)
        })

        // 这个传入一个数组 按顺序执行
        // Promise.all([p1, p2, p3]).then(values => console.log(values))

        // await接受一个async定义返回promise的函数

        async function async1() {
            // 这里按顺序执行
            let result2 = await async2();
            console.log(result2);
            // 异常捕获
            try {
                let result3 = await async3();
            } catch (e) {
                console.log(e);
            }
            
        };


        async function async2() {
            return new Promise(resolve => {
                setTimeout(() => {
                    resolve(10);
                }, 1000)
            });
        }

        async function async3() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    reject("执行异常")
                }, 500)
            })
        }

        async1();
    </script>
</body>
</html>